[package]
name = "ocommit"
version = "0.1.1"
edition = "2024"
authors = ["Bogz Bonny <bogzbonny@protonmail.com>", "The Ocommit Developers"] 
keywords = ["llm", "git", "ollama", "cli"]
description = "quickly create a git commit message with ollama and commit, locally"
documentation = "https://docs.rs/ocommit/latest/ocommit/"
repository = "https://github.com/bogzbonny/ocommit"
categories = ["development-tools"]
readme = "README.md"
license = "MIT"



[dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
ollama-rs = "0.3.2"
serde_json = "1.0.145"
schemars = { version = "1.0.4", features = ["preserve_order"] }
crossterm = "0.29.0"
